spring:
  application:
    name: student-marketplace-backend

  datasource:
    url: jdbc:mysql://localhost:3306/student_marketplace
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 8080

app:
  jwt:
    secret: "change-me-change-me-change-me-change-me-change-me-change-me"
    expiration-ms: 86400000